name: CI BUILD

on:
  push:
    branches-ignore: [ "pages" ]
  pull_request:
    branches-ignore: [ "pages" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install depends
      run: sudo apt install clang-format python3 git gdisk gcc g++ xorriso make mtools curl dos2unix
    
    - name: install limine
      run: |
        git clone https://git.synapseos.ru/Aren/limine.git --branch=v5.x-branch-binary --depth=1
        cd limine && make && cd ..

    - name: build
      run: |
        dos2unix *.sh
        chmod +x build.sh
        ./build.sh

    - name: check root dir
      run: ls -la

    - name: check iso_root
      run: ls -la iso_root

    - name: check bin
      run: ls -la bin
  
  release:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/download-artifact@v3
      
    - name: release
      uses: softprops/action-gh-release@v0.1.15
      with:
        name: Автосборка
        tag_name: autobuild
        draft: true
        files: 'bmosp.hdd', 'kernel.elf', 'bmosp.iso', 'LICENSE'
        body: |
          Нестабильный релиз. Использовать на свой страх и риск. Система расчитана на работу в эмулируемой среде Qemu под процессоры x86_64.
          Мы не несем ответственности за нанесенный ущерб.